services:
  - type: web
    name: mi-app-mapas
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: false
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
